# Generated by Django 2.2.2 on 2019-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estatura', models.CharField(max_length=10)),
                ('peso', models.IntegerField()),
                ('debut', models.IntegerField()),
            ],
        ),
    ]
